# Generated by Django 2.2.5 on 2020-04-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('company_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=60)),
                ('job_description', models.CharField(max_length=120, null=True)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
